export const mockData = {
    users: [{
        id: 1,
        userType: 1,
        email: "devclient0@email.com",
        username: "DevClient0",
        updatedAt: new Date().toUTCString(),
        createdAt: new Date().toUTCString(),
    }, {
        id: 2,
        userType: 1,
        email: "devclient1@email.com",
        username: "DevClient1",
        updatedAt: new Date().toUTCString(),
        createdAt: new Date().toUTCString(),
    }],
    books: [{
        id: 1,
        title: "Permutation City",
        author: "Greg Egan",
        status: 1,
        favourite: false,
        createdAt: new Date().toUTCString(),
        user: 1,
        shelf: 2,
    }, {
        id: 1,
        title: "Neuromacer",
        author: "William Gibson",
        status: 2,
        favorite: false,
        createdAt: new Date().toUTCString(),
        user: 0,
        shelf: 1,
    }, {
        id: 3,
        title: "Industrial Society and Its Future",
        author: "Theodore John Kaczynski",
        status: 3,
        favorite: false,
        createdAt: new Date().toUTCString(),
        user: 1,
        shelf: 1,
    }],
    shelves: [{
        id: 1,
        title: "Science fiction",
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
        topic: 1,
    }, {
        id: 2,
        title: "Computers",
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
        topic: 3,
    }],
    topics: [{
        id: 1,
        title: "Computers",
        description: "Algorithms, programming, etc.",
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
    }, {
        id: 2,
        title: "Fiction",
        description: "Science fiction, fantasy, etc.",
        createdAt: new Date().toUTCString(),
        updatedAt: new Date().toUTCString(),
    }],
};
